# Introduction to Pandas

Pyhon Pandas Vs Excel Limitations by size Complex data transformation Automation Cross Platform Capabilities

1D array             2D array 
[7,2,9]              [5,3,4]
                     [9,1,3] 
series               dataframe

What is a dataframe? 
Example: 
             ID States Population Postal <-- Features 
     row --> 0 California 500000  CA 
             1 Texas      200000  TX 
             2 Florida    220000  FL 
             3 New York   190000  NY

           index          series
           
Very similar to an Excel spreadsheet

EXCEL --> PANDAS

Worksheet    Dataframe 
Column        Series 
Row Heading    Index 
Row             Row 
Empty Cell      NaN

How to create a Dataframe 
1.Arrays 1D arrays are columns and 2D arrays are dataframes 
Numpy Array np.array([[1,4],[2,5],[3,6]]) 
ID col1 col2
 0   1   4
 1   2   5
 2   3   6
or  
List Arrays
    data = [[1,4],[2,5],[3,6]]
    
2.Dictionaries 
my_dict = {'Column Name':'Data'} 
             series(1D array) 
3.CSV File

## Creating a Dataframe from an Array¶

### Option 1

In [3]:
import pandas as pd
import numpy as np

In [4]:
# creating an array
data = np.array([[1,4],[2,5],[3,6]]) 
data

array([[1, 4],
       [2, 5],
       [3, 6]])

In [5]:
# creating a dataframe
df = pd.DataFrame(data, 
                  index = ["row1",'row2','row3'],
                  columns = ['col1','col2'])

In [6]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

### Option 2

In [7]:
data = ([[1,4],[2,5],[3,6]])

In [8]:
# creating a dataframe
df = pd.DataFrame(data, 
                  index = ["row1",'row2','row3'],
                  columns = ['col1','col2'])

In [9]:
# showing the dataframe
df

      col1  col2
row1     1     4
row2     2     5
row3     3     6

### Option 3

In [10]:
# Lists used for this example
states = ['California', 'Texas', 'Florida', 'New York']
population = [300000,290000,2200000,1900000]

In [11]:
# Storing Lists within a dictionary
dict_states = { 'States':states, 'Population':population}

In [12]:
# Creating the dataframe
df = pd.DataFrame(dict_states, index=[f"row {i}" for i in range(len(states))]
)

In [13]:
# Showing the dataframe
df

           States  Population
row 0  California      300000
row 1       Texas      290000
row 2     Florida     2200000
row 3    New York     1900000

In [14]:
# reading the csv file
df_exams = pd.read_csv("StudentsPerformance.csv")

In [15]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [16]:
# show first 5 rows in a dataframe
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [17]:
# show last 5 rows in a dataframe
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [18]:
# show last n rows in a dataframe
df_exams.tail(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
990,male,group E,high school,free/reduced,completed,86,81,75
991,female,group B,some high school,standard,completed,65,82,78
992,female,group D,associate's degree,free/reduced,none,55,76,76
993,female,group D,bachelor's degree,free/reduced,none,62,72,74
994,male,group A,high school,standard,none,63,63,62
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [19]:
# show first n rows in a dataframe
df_exams.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [20]:
# getting acces to shape attribute
df_exams.shape

(1000, 8)

In [21]:
# display n rows
pd.set_option('display.max_rows',10)

In [22]:
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Attributes

A value associated with an object 
    referenced by name using a dotted expression
    EX:
        df.columns

In [23]:
# getting acces to the shape attribute gives dimensions
df_exams.shape

(1000, 8)

In [24]:
# will return range of indicies
df_exams.index

RangeIndex(start=0, stop=1000, step=1)

In [25]:
#returns list of columns
df_exams.columns

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course', 'math score', 'reading score',
       'writing score'],
      dtype='object')

In [26]:
# returns data type of each column 
df_exams.dtypes

# object refers to a string

gender                         object
race/ethnicity                 object
parental level of education    object
lunch                          object
test preparation course        object
math score                      int64
reading score                   int64
writing score                   int64
dtype: object

# Methods

A group of related statemnets that perform a specific task

Python built in
    max 
    min 
    len 
These are also built into pandas

In [27]:
# show first 5 columns
df_exams.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [28]:
#show last 5 columns
df_exams.tail()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [29]:
# Show the info of the dataframe
df_exams.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB

In [30]:
# describe basic statistics of the dataframe
df_exams.describe()

       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

# Functions

A function which is defined inside a class body 
    EX: 
        df.head()

In [31]:
# obtain the length of the dataframe (num rows)
len(df_exams)

1000

In [32]:
# obtain highest index
max(df_exams.index)

999

In [33]:
# obtain lowest index
min(df_exams.index)

0

In [34]:
# obtain data type
type(df_exams)

pandas.core.frame.DataFrame

In [35]:
# round the values of the dataset
round(df_exams,2)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Selecting ONE Column from a DataFrame

In [36]:
# select a column with [] (preferred way)
df_exams['gender']

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [37]:
# check out the data type of a column
type(df_exams['gender'])

pandas.core.series.Series

In [38]:
# series: attributes and methods
df_exams['gender'].index

RangeIndex(start=0, stop=1000, step=1)

In [39]:
df_exams['gender'].head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [40]:
# select a column with .
df_exams.gender

0      female
1      female
2      female
3        male
4        male
        ...
995    female
996      male
997    female
998    female
999    female
Name: gender, Length: 1000, dtype: object

In [41]:
df_exams.gender.index

RangeIndex(start=0, stop=1000, step=1)

In [42]:
df_exams.gender.head()

0    female
1    female
2    female
3      male
4      male
Name: gender, dtype: object

In [43]:
# common pitfalls with . 
# df_exams.math score      this will cause an error and using an _ will not reference the correct column

In [44]:
df_exams['math score']

0      72
1      69
2      90
3      47
4      76
       ..
995    88
996    62
997    59
998    68
999    77
Name: math score, Length: 1000, dtype: int64

# Selecting TWO or MORE Columns from a DataFrame

In [45]:
# select 2 columns using [[]]
df_exams[['gender','math score']]

     gender  math score
0    female          72
1    female          69
2    female          90
3      male          47
4      male          76
..      ...         ...
995  female          88
996    male          62
997  female          59
998  female          68
999  female          77

[1000 rows x 2 columns]

In [46]:
# check out the data type of the selection
type(df_exams[['gender','math score']])

# this makes sense because it is a 2d array while the 1d array was a series

pandas.core.frame.DataFrame

In [47]:
# select 2 or more columns using [[]]
df_exams[['gender','math score','reading score','writing score']]

     gender  math score  reading score  writing score
0    female          72             72             74
1    female          69             90             88
2    female          90             95             93
3      male          47             57             44
4      male          76             78             75
..      ...         ...            ...            ...
995  female          88             99             95
996    male          62             55             55
997  female          59             71             65
998  female          68             78             77
999  female          77             86             86

[1000 rows x 4 columns]

In [48]:
# we cant select 2 or more columns with the "." 
# df_exams.'gender','math score'

# Adding a NEW Column

In [51]:
# adding with a scalar value
df_exams['language score'] = 70
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,70
1,female,group C,some college,standard,completed,69,90,88,70
2,female,group B,master's degree,standard,none,90,95,93,70
3,male,group A,associate's degree,free/reduced,none,47,57,44,70
4,male,group C,some college,standard,none,76,78,75,70
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,70
996,male,group C,high school,free/reduced,none,62,55,55,70
997,female,group C,high school,free/reduced,completed,59,71,65,70
998,female,group D,some college,standard,completed,68,78,77,70
999,female,group D,some college,free/reduced,none,77,86,86,70

In [54]:
# adding with an array
# create an array with length of n
language_score = np.arange(0,1000)

In [55]:
len(language_score)

1000

In [57]:
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,0
1,female,group C,some college,standard,completed,69,90,88,1
2,female,group B,master's degree,standard,none,90,95,93,2
3,male,group A,associate's degree,free/reduced,none,47,57,44,3
4,male,group C,some college,standard,none,76,78,75,4
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,995
996,male,group C,high school,free/reduced,none,62,55,55,996
997,female,group C,high school,free/reduced,completed,59,71,65,997
998,female,group D,some college,standard,completed,68,78,77,998
999,female,group D,some college,free/reduced,none,77,86,86,999

In [70]:
# Create random integer numbers between 1 and 100
language_score = np.random.randint(1,100,1000)

In [71]:
df_exams['language score'] = language_score
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score
0,female,group B,bachelor's degree,standard,none,72,72,74,43
1,female,group C,some college,standard,completed,69,90,88,84
2,female,group B,master's degree,standard,none,90,95,93,29
3,male,group A,associate's degree,free/reduced,none,47,57,44,68
4,male,group C,some college,standard,none,76,78,75,50
...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,45
996,male,group C,high school,free/reduced,none,62,55,55,10
997,female,group C,high school,free/reduced,completed,59,71,65,62
998,female,group D,some college,standard,completed,68,78,77,88
999,female,group D,some college,free/reduced,none,77,86,86,32

In [65]:
min(language_score)
max(language_score)

np.int32(99)

In [74]:
df_exams.describe()

       math score  reading score  writing score  language score
count  1000.00000    1000.000000    1000.000000     1000.000000
mean     66.08900      69.169000      68.054000       50.631000
std      15.16308      14.600192      15.195657       28.692998
min       0.00000      17.000000      10.000000        1.000000
25%      57.00000      59.000000      57.750000       26.000000
50%      66.00000      70.000000      69.000000       52.000000
75%      77.00000      79.000000      79.000000       75.000000
max     100.00000     100.000000     100.000000       99.000000

In [75]:
# create random float numbers
np.random.uniform(1,100,1000)

array([84.93586129, 40.69424896, 50.20423669, 26.3373436 , 93.36392962,
       78.28267021, 32.93065585, 71.68237164, 52.43062669, 26.35191379,
       30.59744777, 41.60939575, 76.4741481 , 18.36542518, 30.69800927,
       58.96015949, 56.86445217, 26.80357637, 98.13313532, 55.99891029,
       40.39853264, 58.35148595, 24.30538922, 66.21795111, 16.74332136,
       99.95199245, 13.80746238, 51.87128797, 72.07570657, 65.78594127,
       54.21959632, 14.12452662, 84.72121665, 63.08914659, 85.46704062,
       39.17485277, 70.67603678, 37.55033938, 82.46839834, 93.58762055,
       50.7657443 , 47.16894965, 75.86591373, 73.10467571, 56.88822492,
       71.05726397, 17.55939391, 53.03507565, 23.82168703, 88.21182799,
       41.98172546, 89.3505141 , 78.21345316, 83.51923528,  3.00327548,
       97.17147119, 86.22605135, 20.86333748, 65.89221971, 90.49546092,
       56.0107261 , 30.9669508 , 38.52008481, 93.45421653, 72.54535341,
       34.66350125, 10.24693303, 13.78470537, 43.8767006 , 12.13988595,
       52.5502414 , 62.33859427,  1.22242204, 11.9577309 , 87.37670123,
       11.86805237, 84.25810012, 18.9173902 ,  4.36871607, 56.39045823,
       19.13944566, 40.82236545, 63.40880619, 19.22888456, 51.32959479,
       97.45497111, 21.9572496 , 32.4737319 , 93.3724658 , 11.76373609,
       53.35706554, 68.7224183 , 74.61027177, 97.36490817, 32.25815729,
       21.98609341, 69.81572069, 57.89610915, 86.47745073, 58.85216529,
       99.23157652, 76.5973562 , 76.94643308, 16.99385366, 54.44529975,
       86.62459569, 81.96489815, 10.87523215, 40.6046034 , 96.71995093,
       39.91565926, 56.30388039, 18.18438228, 83.55531993, 82.03731534,
       10.06740651, 63.42324068, 81.01190783, 72.40368567, 23.20507371,
       77.89677809, 17.40067018, 13.45365196, 34.96184817, 24.33506643,
       93.57325047, 15.13383108, 82.53964564, 61.32345927, 53.35507673,
       25.24733196, 75.72617302, 83.57565328,  3.91369635, 42.41920633,
       92.08379822, 29.47283356, 64.89321127, 99.30119824, 85.73317034,
       54.15826113,  7.49771651, 53.54867523,  8.59904122, 61.33968656,
        6.01221842, 14.35095283, 82.39990855, 77.12998415, 28.5535903 ,
       16.99768261, 83.49568975, 10.69109068, 26.96471505, 51.95325554,
       14.95522501, 50.38344684, 64.3401641 , 47.92504995, 88.74235976,
       97.38391967, 16.42397385, 56.2351726 , 74.04561014, 56.56874518,
       80.28607793, 92.56739386, 60.10900139, 17.89693989, 67.03049625,
       27.63362218, 49.14687887, 40.3696508 , 83.73910208, 49.17923362,
       89.06609221, 84.41818261, 33.08840348, 66.93916735, 14.22637253,
       28.84093818, 25.69040417, 25.82162077, 65.56907179, 75.13111916,
       73.18668043, 96.86385862, 70.47254773, 49.30951869, 48.17589442,
       17.45591918,  2.50680062, 82.69129623, 51.41902251,  6.66302201,
       26.48356173, 61.36319596, 38.97091378, 81.89269005, 89.58511911,
       66.07726693, 70.7695858 , 50.00224726,  6.43966984, 43.92806128,
       27.90457283, 56.23933063, 35.77685511, 75.69009167, 83.21673822,
       93.7515748 , 34.26303738, 52.46352769, 32.35822098, 84.82323605,
       10.12277427, 17.35061517, 44.62339898, 24.78899896, 18.18560256,
       85.52325718, 51.85874352, 31.3578632 , 41.92512899, 10.64170439,
       29.89938443, 51.68925365, 55.2198107 , 70.48104943, 90.81055142,
       73.26605822, 18.46026877, 81.4144835 , 84.03539938, 61.97435279,
       48.58333872, 71.10301939,  1.20636179, 55.89333099, 73.76703787,
       86.17152682, 78.63375563, 43.82      , 84.98571048, 12.24244874,
       56.55207284, 45.05253528, 34.71233595, 37.73767145, 54.36185615,
       79.13795595, 92.87348912, 49.94758942, 48.36846442,  7.86024608,
       57.01595756, 73.81813693, 85.99049861, 48.05726979, 13.85114498,
       71.77811529, 48.55998092, 87.52665906, 47.50930691, 37.38655521,
       92.70100256, 73.92362974, 17.85966317, 28.39600832, 23.29540228,
       50.42175563,  4.80164452, 56.00856811, 51.57115335, 60.95494321,
       77.90783569, 45.97697171, 49.44980849, 39.11671749, 43.58580535,
        8.65354108, 95.67959956,  3.857469  , 59.08498042, 69.1832799 ,
       25.17453243, 49.03600145, 40.48105356, 57.01405227,  8.00531561,
       25.51845849,  4.01404637, 59.16398575, 75.32650042, 89.00095269,
       78.19425029, 34.35134963, 78.63243373, 65.00762133,  6.89726013,
       89.70445043,  3.59345478, 42.07285987, 91.99407052,  9.67274216,
       49.33959012, 29.96964251, 30.36299079, 80.04808916, 49.95308862,
       37.60324209, 79.61786194, 39.83215802, 57.16054896, 30.40951208,
       94.08073456, 53.68062915, 44.09999614, 10.75823129, 29.98115941,
       14.12600619, 10.67479132, 45.74427875, 42.18217657, 39.10026054,
       34.96582559, 91.59207798, 85.10127986, 71.99064034, 85.23833232,
       13.9071507 , 39.46803423,  6.79184592, 42.26846929, 27.25964254,
       79.77986262, 76.92954979, 35.46408715, 85.98749851, 98.02177131,
        9.792533  , 68.41236475, 81.99813799, 83.95873622, 20.53491039,
       32.66717425, 28.46926672, 89.95789314,  7.26704515, 11.33925276,
        4.77316444, 58.07217658, 63.66889403, 81.15192573, 22.31759221,
       26.72504459, 83.46192492, 46.18054453, 34.37634151, 95.45591987,
        1.09610751, 21.51933957, 16.16465529, 81.70536545, 74.27232263,
       91.7133064 , 88.29972573, 22.35526432, 77.16739097, 15.91745631,
        1.08079401, 77.74509076, 34.7768018 , 91.57307247, 83.17526059,
       45.06567744,  9.05368513, 46.34872217, 99.48043384, 23.6867287 ,
       40.13750177, 31.46831415, 96.08371583, 51.81388834, 45.39394144,
        1.6917556 , 37.69000299, 85.30662457, 63.52629432, 94.55608967,
        7.01901604, 62.84422372,  3.80380888, 33.33213728, 69.86843487,
       24.33946175, 74.74159387, 48.03174031, 38.41227626, 10.60162351,
       32.24589938, 43.89800119, 48.55286706, 27.76590161, 24.90355646,
       35.7480764 , 95.3786935 , 18.39780298, 33.33041713, 55.12200301,
        3.72065956, 69.04500339, 42.89203613, 15.92176472, 54.49832066,
       34.05807406, 82.42274183, 96.25732586, 47.55470883, 97.97699114,
       52.94673677, 25.07559271,  8.77237685, 59.60811171, 87.02432157,
       50.96248814, 81.90701131, 82.23710027, 82.45107147, 84.99755564,
       94.53216255, 88.41324419, 50.04661846, 75.13698427,  4.36092382,
       62.60458076, 74.37913848, 71.90033713, 25.87962874, 18.17690447,
       42.25866563, 24.9556398 , 30.97913028, 89.3894795 , 45.72826404,
       50.56273232, 31.50746595, 26.14969376, 60.0889839 , 47.49652425,
       61.15588932, 69.20941778, 10.46420884, 38.74877627, 49.66616096,
       24.86770369, 33.20824877,  2.10519158,  9.19058447, 75.23105696,
       38.11938981, 11.57666317, 49.31661226, 22.59794496, 54.86302149,
       87.00014262, 46.91782547, 45.74362419, 36.79669514, 30.28065749,
       47.42402057, 73.72110863, 28.79009967, 38.69102257,  3.39756851,
        4.8656534 , 85.8744751 , 47.38996575, 49.96852303,  5.2216189 ,
       18.84972202, 13.4793059 , 31.35602611, 85.25203254, 65.92916281,
       65.95245145, 44.95479146, 18.17013044, 79.49371524, 76.77926244,
       23.83259923, 70.68741521, 92.37189618,  3.37820913,  3.95694165,
       52.22594986, 32.45346401, 20.45792151, 18.46151378, 58.93684317,
       59.29791571, 71.63302928, 97.03694663, 25.80601313, 94.71385284,
        6.90284922, 64.73319892, 45.28217148, 59.23120102, 94.91179886,
       93.49857385, 13.59490846, 64.52292321, 40.22320703, 86.25031377,
       11.98180827,  4.07595242, 93.7852074 , 35.09849656, 66.38479979,
        6.20419824,  4.03710852, 22.18014215, 44.88230976, 20.80320036,
       96.08385957, 68.0955902 , 66.03370231, 97.26724741, 64.88021769,
       92.65364754, 52.46156772, 88.0868749 , 15.54250635, 45.32806386,
       25.41085977, 93.80407695, 38.4167612 , 22.10477416, 32.72132874,
       97.6620047 , 14.65857497, 90.33857382, 84.93210098, 69.08698698,
       92.09339864, 12.18582554, 49.64934108, 99.73136781, 62.9967867 ,
       65.17049757, 59.07151153, 44.55094993, 73.96323359, 37.53856   ,
       67.3293402 , 91.8058082 , 91.89406287, 90.5268508 , 51.50913677,
       19.83201042, 24.54064818, 46.80879261, 10.3626609 , 11.37527843,
       70.79223117, 99.05119209, 13.18921899, 91.65657867,  4.65535766,
       74.22441806, 35.82245877, 59.48786012, 60.2423979 , 86.69943138,
       18.24449211, 60.15539978, 17.85405106, 51.87094035, 47.59742319,
       42.87785878, 24.26866326, 52.15950195, 25.9787087 , 97.83793902,
       48.47239301, 46.53767637,  6.8121764 , 90.57697377, 74.04344162,
       28.90522499, 62.3047793 ,  6.38881753, 37.5828194 , 15.49931379,
       70.82603692, 88.38758055, 98.58740566, 83.43370837, 63.98421463,
        7.36533239, 28.86645106, 99.99636176, 16.87522945, 73.62839993,
       60.67111104, 21.58740331, 41.41868897, 49.71567052, 53.48662883,
       83.93468071, 24.34621175, 71.67443291,  8.76479908, 27.6914936 ,
       30.16049616, 94.15945434, 36.05425565, 10.59842309, 43.6383988 ,
       10.73880345, 31.79189009, 60.4373421 , 98.66287181, 24.80497206,
       60.43930353, 97.65967681,  6.29168028, 72.27121339, 76.71634521,
       76.32415642, 53.09986718, 73.83981811, 68.32226195, 53.9032619 ,
       67.43471877, 52.462416  , 30.8503658 , 74.08445072, 48.89521066,
       10.22523704, 65.26790311, 25.79683409, 97.01797446, 11.35754466,
        1.59251394, 50.90355727, 51.47587627, 38.87314371, 62.82265883,
       10.59654046, 69.58996183, 92.83718954, 51.02079293, 88.79877105,
       58.25863728, 59.84851824, 43.50676553, 27.9054543 , 91.99163696,
        9.08898038, 93.21111979, 44.76056382, 91.51999273, 87.64489115,
       28.05314168, 49.61394007, 69.26750161, 77.02392116, 84.61253495,
       53.15770008, 59.99699003, 58.50034317, 50.0079445 , 22.44220552,
        2.68651427, 11.67837989, 90.21182384, 21.39393209, 21.2709581 ,
       90.18892802, 52.02452793, 46.90426484, 57.1412862 , 39.94708365,
       52.376348  , 53.15227649, 23.88430342, 68.7159585 , 86.39256597,
       95.80739735, 73.99017001, 75.91598233, 55.77788747, 13.08766713,
       26.15819185, 60.79253608, 42.392398  , 54.12615281, 76.31085268,
       22.84599368, 93.20655008, 52.43587511, 23.91441396, 39.83405775,
       77.20328091, 41.31528865, 79.37099574, 80.04340417,  5.31587478,
       84.43769736, 76.60306566, 57.84747938, 47.44846077,  2.17638263,
       96.15848782, 47.4425712 , 22.94660847, 62.85193181, 66.25223127,
       48.88063374, 98.38192022, 88.01163341, 17.84690786, 82.20044448,
       32.65199568, 78.1148518 , 39.92433221, 48.75443521, 24.92330423,
        8.15819577,  8.45424343, 45.87069829, 54.08056672,  2.25705265,
       62.03366365, 29.57405091, 38.91636721, 63.62461725, 61.9257176 ,
       29.42114766, 17.15791874, 43.57216071, 48.77216118, 45.19984242,
       23.79428728, 67.85207598, 13.55225293,  9.99217701, 72.15766151,
       59.37070796, 23.06475627, 70.21787002, 32.84090994, 74.28616173,
        4.09612108, 42.17948416, 42.12718967, 29.02067711, 94.05200266,
       86.59246597, 16.86872714, 58.4964637 , 43.75840921, 55.75632386,
       14.60979185, 98.0159051 , 31.94101927, 45.60523362, 69.52595633,
       93.39234719, 41.80899181, 47.40089044,  9.03401014, 76.98538084,
       64.39956729, 35.95833681, 65.88801949,  8.97205021,  9.17458004,
        2.22420604, 97.77998688, 39.06192948, 59.85389757, 25.15958632,
       31.49664278, 20.68240926, 19.43779135, 95.76530221, 82.51593806,
       22.83942165, 48.00397823,  3.71200864, 60.07357193, 70.43554979,
       71.68514324, 33.40792175,  5.75857841, 51.6764618 , 63.1903485 ,
       18.23700545, 84.43005885,  9.20327742, 24.1355751 , 33.23279972,
       88.4174028 , 67.33048024, 44.81339538, 95.18305138, 55.49636422,
        5.00456243, 29.80467573, 79.15901171, 97.46021464, 95.00916522,
       52.14703313, 52.70779007, 67.91324424, 59.84456112, 29.24802924,
       38.21670627, 58.17126106, 97.69296405, 54.35581365,  5.65013269,
       31.57171062, 43.01491313, 86.7401184 , 33.09320156, 63.51523199,
       51.69758511, 61.39656999, 11.1598566 , 70.09784414, 92.08727324,
        8.65047786, 11.34564571, 11.20681189, 80.68938547, 87.30959194,
        6.92671994, 73.51227803, 30.62254155, 80.59873133, 97.78699393,
       66.91529105, 72.57219041, 99.14758105, 37.1993518 , 40.64119809,
       61.62430752,  2.166408  , 76.93616896, 22.11977262, 91.03752351,
       58.21054089, 70.72352259,  6.50743175, 75.73651359, 78.13386268,
       73.50675807, 45.7476469 , 27.45592815, 64.0282276 ,  3.66077606,
       25.36665623, 87.61091114, 28.72694767,  4.96678979, 23.46657975,
       55.59317398, 84.17279238, 70.67812951, 80.12856981, 55.19250828,
        2.54025265, 24.36870918, 95.70770819, 53.19711162, 20.61984757,
       78.74777256, 23.09366846, 43.15032811,  7.82085719, 27.79045177,
        8.03638714, 81.60629241, 88.89695862, 77.47018246, 82.59431853,
       67.66446791, 93.36507469, 83.33755648, 16.30666892, 30.08998074,
       94.47935896, 38.62231694, 90.03289144, 47.75619649, 66.6235031 ,
       59.80515241, 26.38867892, 77.47737926, 48.79956385, 94.20715122,
       81.07235769, 26.28388127, 28.85666311, 20.20996525, 24.81986177,
       17.73010407, 16.31338274, 10.48995298,  3.91412994, 94.95088583,
       13.59139014, 64.47182524, 15.2961538 , 67.07346443, 31.97990636,
        9.83671265, 19.96501468, 21.60942926, 82.58722078, 78.08528337,
       41.73736009, 93.12836336, 80.6635722 , 36.12774187, 32.95512451,
       38.08513404, 39.49645219, 33.23716223, 42.85629022, 38.65278732,
       74.74310357, 16.67541525, 54.17138283, 58.98031526, 66.21281317,
       82.74157263,  3.24667807, 55.78730371, 99.19738485, 79.57065979,
       90.42624338, 45.22754495, 21.67395505, 70.67847679, 75.59316015,
        2.08049239, 50.65267406, 71.27071624, 15.44949961,  1.8993537 ,
       74.21614454, 27.67696441, 91.37392487, 48.94129334, 91.1457628 ,
       18.8064424 , 89.14636493, 69.7687177 , 79.47076661, 10.08552465,
       61.7235151 , 15.72882765, 97.45934874, 73.71377287, 97.7662938 ,
       75.19035415, 74.64869486, 84.99117185, 64.37401567, 61.54345989,
       79.32135443, 26.99343568, 15.80170762, 45.55868395, 76.2486845 ,
       70.37300856, 66.84891029, 24.48031571, 55.28561627, 26.61868819,
       21.61729536, 92.80621266, 12.57427982,  9.81833968, 41.8983898 ,
       52.55503149, 82.32124999, 15.23594505, 15.11896873, 16.59472313,
       81.57358519, 38.13528317,  8.71808042,  9.52309481, 88.67942509])

In [78]:
np.round(2)

np.int64(2)

# Assign

In [ ]:
# assign()
# when to use?
# adding multiple columns in a single line of code
# when you need to overwrite the values of an existing columns (best practice)

In [80]:
# create random numbers for our new score columns
score1 = np.random.randint(1,100,1000)
score2 = np.random.randint(1,100,1000)

In [84]:
# create a series using the random numbers
series1 = pd.Series(score1, index = np.arange(0,1000))
series2 = pd.Series(score2, index = np.arange(0,1000))

In [89]:
# using asssign to add multiple columns
df_exams.assign(score1 = series1, score2 = series2)
# using assign creates a copy it does not overwrite the dataframe therefor you must assign it 
df_exams = df_exams.assign(score1 = series1, score2 = series2)
df_exams

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,group B,bachelor's degree,standard,none,72,72,74,43,51,17
1,female,group C,some college,standard,completed,69,90,88,84,11,3
2,female,group B,master's degree,standard,none,90,95,93,29,23,74
3,male,group A,associate's degree,free/reduced,none,47,57,44,68,38,94
4,male,group C,some college,standard,none,76,78,75,50,58,8
...,...,...,...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95,45,73,53
996,male,group C,high school,free/reduced,none,62,55,55,10,25,76
997,female,group C,high school,free/reduced,completed,59,71,65,62,71,87
998,female,group D,some college,standard,completed,68,78,77,88,83,62
999,female,group D,some college,free/reduced,none,77,86,86,32,7,2

# Insert

In [91]:
# inserts new column at specific postion or index
df_exams.insert(1,'Test', series1)
# insert does not create a copy it directly affects the dataframe

ValueError: cannot insert Test, already exists

In [92]:
df_exams

,gender,Test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2
0,female,51,group B,bachelor's degree,standard,none,72,72,74,43,51,17
1,female,11,group C,some college,standard,completed,69,90,88,84,11,3
2,female,23,group B,master's degree,standard,none,90,95,93,29,23,74
3,male,38,group A,associate's degree,free/reduced,none,47,57,44,68,38,94
4,male,58,group C,some college,standard,none,76,78,75,50,58,8
...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,73,group E,master's degree,standard,completed,88,99,95,45,73,53
996,male,25,group C,high school,free/reduced,none,62,55,55,10,25,76
997,female,71,group C,high school,free/reduced,completed,59,71,65,62,71,87
998,female,83,group D,some college,standard,completed,68,78,77,88,83,62
999,female,7,group D,some college,free/reduced,none,77,86,86,32,7,2

# Math Operations

## Operations in Columns

In [95]:
# select a column and calculate total sum
df_exams['math score'].sum()

np.int64(66089)

In [96]:
# count, mean, std, max, min
df_exams['math score'].count()

np.int64(1000)

In [97]:
df_exams['math score'].mean()

np.float64(66.089)

In [98]:
df_exams['math score'].std()

15.163080096009468

In [99]:
df_exams['math score'].max()

100

In [100]:
df_exams['math score'].min()

0

In [102]:
# easier calculation with describe
df_exams.describe()

,Test,math score,reading score,writing score,language score,score1,score2
count,1000.000000,1000.00000,1000.000000,1000.000000,1000.000000,1000.000000,1000.000000
mean,50.979000,66.08900,69.169000,68.054000,50.631000,50.979000,49.074000
std,28.863778,15.16308,14.600192,15.195657,28.692998,28.863778,29.273118
min,1.000000,0.00000,17.000000,10.000000,1.000000,1.000000,1.000000
25%,26.000000,57.00000,59.000000,57.750000,26.000000,26.000000,23.000000
50%,51.000000,66.00000,70.000000,69.000000,52.000000,51.000000,48.000000
75%,77.000000,77.00000,79.000000,79.000000,75.000000,77.000000,75.000000
max,99.000000,100.00000,100.000000,100.000000,99.000000,99.000000,99.000000

## Operations in Rows

In [103]:
# calculating the sum in a row
df_exams['math score'] + df_exams['reading score'] + df_exams['writing score']

0      218
1      247
2      278
3      148
4      229
      ...
995    282
996    172
997    195
998    223
999    249
Length: 1000, dtype: int64

In [117]:
# calculate the average score and assign te result to a new column
df_exams['sum_of_scores'] = (df_exams['math score'] + df_exams['reading score'] + df_exams['writing score'])/3

In [116]:
df_exams.drop("average",axis=1, inplace=True)

In [119]:
df_exams.round(2)

,gender,Test,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,language score,score1,score2,sum_of_scores
0,female,51,group B,bachelor's degree,standard,none,72,72,74,43,51,17,72.67
1,female,11,group C,some college,standard,completed,69,90,88,84,11,3,82.33
2,female,23,group B,master's degree,standard,none,90,95,93,29,23,74,92.67
3,male,38,group A,associate's degree,free/reduced,none,47,57,44,68,38,94,49.33
4,male,58,group C,some college,standard,none,76,78,75,50,58,8,76.33
...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,female,73,group E,master's degree,standard,completed,88,99,95,45,73,53,94.00
996,male,25,group C,high school,free/reduced,none,62,55,55,10,25,76,57.33
997,female,71,group C,high school,free/reduced,completed,59,71,65,62,71,87,65.00
998,female,83,group D,some college,standard,completed,68,78,77,88,83,62,74.33
999,female,7,group D,some college,free/reduced,none,77,86,86,32,7,2,83.00